# Generated by Django 3.2.8 on 2021-10-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.FileField(upload_to='photoalbum/image'),
        ),
    ]
